### ISSUE TITLE
TimeoutUser appears to not work

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/StreamingClientLibrary#100]
I have been trying to debug this all morning and I am not sure if there is some issue with Twitch or a possible bug somewhere in the library.

I have a TwitchConnection object based off an OAuthToken for a channel owner.
The token was created with many scopes, including  Twitch.Base.OAuthClientScopeEnum.moderator__manage__banned_users.
I have a ChatClient created from that connection.
The ChatClient can send messages in chat as the channel owner and can receive chat messages with no issues.

If I use the ChatClient.TimeoutUser method passing in the channel owner UserModel, the person to time out UserModel and the duration in seconds, nothing happens.   The method call does not throw any exceptions and the user is not timed out in the channel.

I have verified that both the channel owner UserModel and the time out person UserModel are correct.  The timeout in seconds is being set to 300.

**Comment by mphacker** [comment]
Using Postman I used the same OAuth token and client-id as the app and manually posted to the API endpoint using the exact same data (broadcaster_id and user_id) and it successfully timed out the user.  I believe this rules out a token issue.  I am looking at the TimeoutUser method and it is just a redirect to the connection.NewAPI.Chat.TimeoutUser method.  Looking at the last method which has the PostAsync, I am not seeing any issues that stand out.

**Comment by mphacker** [comment]
Error message coming back from Post is:
"{\"error\":\"Bad Request\",\"status\":400,\"message\":\"Missing required parameter \\\"user_id\\\"\"}"

This is not bubbling up so the only way to find out if there was an error was to download the library source add a variable to catch the response and then break after it.

It appears that the body is not formed correctly.  It looks like the data: node is missing from the body.  Looking into the source to see if that can easily be added.

**Comment by mphacker** [comment]
See pull request for fix.

**Comment by SaviorXTanren** [comment]
#101
