### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Lulalaby** [SaviorXTanren/StreamingClientLibrary#115]
Hey there!

Thanks for making this lib. I'm missing a real documentation tho.
Would it be possible to request one?

I would suggest using something like docfx :heart:

**Comment by SaviorXTanren** [comment]
I don't have the time to invest in a full documentation set. The library is fairly self-documenting and there are plenty of samples that I've included with how to use a lot of common scenarios.

What specifically are you having difficulty understanding?
