### ISSUE TITLE
UpdateUserRoles() currently does not return the newly updated user (Mixer issue)

### ISSUE THREAD

**Issue by SaviorXTanren** [SaviorXTanren/StreamingClientLibrary#15]
There is a bug on Mixer's end where the result from the API call in UpdateUserRoles() is missing information, so we can not correctly process the result. The API works and will subsequently update the user's roles for that channel, but we can only return a true/false answer for whether it succeeded. You will then need to call GetUsersWithRoles() and find the user you just updated.

Once Mixer has fixed this issue, I'll update the API to return the correct result.

**Comment by TyrenDe** [comment]
Update: I just checked, and they are STILL not returning the groups data in the response.
