### ISSUE TITLE
InteractiveClient.DeleteScene() currently gets no response returned when called (Mixer issue)

### ISSUE THREAD

**Issue by SaviorXTanren** [SaviorXTanren/StreamingClientLibrary#5]
There is currently a bug in Mixer's API where calling the deleteScenes does not return a response. Awaiting on a fix by the Mixer team.

**Comment by TyrenDe** [comment]
Update: I just tested this and I got a response that matches their protocol: https://dev.mixer.com/reference/interactive/protocol/protocol.pdf

A successful response is:
```
{
    "type": "reply",
    "result": null,
    "error": null,
    "id": 123
}
```

The response I got was:
```
{
  
    "seq":9,
  
    "result":null,
    "error":null,
    "data":null,
    "resultObject":null,
    "errorObject":null,
    "dataObject":null,
    "type":"reply",
    "id":6
}
```

Clearly it has more stuff (probably a bug in Mixer), but they only give back useful info on failure. (error is set).  I'm not sure they plan to ever add support for anything more than what you have already.
