### ISSUE TITLE
No ability to use a "bot" account with Twitch provider

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/StreamingClientLibrary#67]
It appears that the chat client and pubsub client both are based off of the TwitchConnection.  This won't work in situations where a person wants their bot to run under a different account than the broadcasters account.    

Any thoughts on how to get a twitchConnection under a bot login account that has mod rights on the broadcaster's channel and then connect to chat and pubsub for the broadcaster channel?

**Comment by mphacker** [comment]
I forgot about the chat join command... and registering events with pubsub.  All good

**Comment by SaviorXTanren** [comment]
You would make multiple TwitchConnection objects, one per account you're trying to log in under. Each one is going to have it's own OAuth token and access. So one for the "Streamer" account and one for the "Bot" account.
