### ISSUE TITLE
Twitch chat websocket disconnects with status of WebSocketCloseStatus = InternalServerError

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/StreamingClientLibrary#68]
I have been noticing that after a period of time (seems to be around 30 minutes or so) the Twitch chat client tosses a disconnect event with a status of InternalServerError.   I haven't been able to identify a root cause for the issue yet.

**Comment by SaviorXTanren** [comment]
I would need to know the details of the actual error, that's not enough information to go off of.
