### ISSUE TITLE
twitchConnection.NewAPI.Users.GetFollows throws error when retrieving large list of followers

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/StreamingClientLibrary#69]
Tried something like:
`FollowersCount = (await twitchConnection.NewAPI.Users.GetFollows(null, Streamer.UserId, int.MaxValue)).Count();`

Error:
System.ArgumentException: An item with the same key has already been added. Key: after
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Twitch.Base.Services.NewAPI.NewTwitchAPIServiceBase.GetPagedDataResultAsync[T](String requestUri, Int32 maxResults)
   at Twitch.Base.Services.NewAPI.UsersService.GetFollows(String fromID, String toID, Int32 maxResults)

Assuming Twitch API is duplicating accounts in the returned list.  Looking into the API it seems that the max number of followers that can be returned is 100.   I do see that the JSON response to the `https://api.twitch.tv/helix/users/follows?to_id=<user ID>` API includes a total field.    

Maybe need to create a variation of the GetFollows method that only returns the count, or update the response object to include the total and then a dictionary of followers.

**Comment by SaviorXTanren** [comment]
If you're intention is to simply get the follower count and not a list of follower, than that should be a separate method to be added.
