### ISSUE TITLE
Some unit tests currently do not work fully due how the APIs function

### ISSUE THREAD

**Issue by SaviorXTanren** [SaviorXTanren/StreamingClientLibrary#7]
Some of the unit tests for various APIs do not work correctly in a unit test fashion due to how the API actually functions. For example, the InteractiveClient.CaptureSparkTransaction() method requires a spark transaction ID to work correctly. However, this would involve a user using an interactive control on your Mixer page to generate the spark transaction that is sent to the client. All unit tests that fail in this way have documentation on the unit test explaining why they do not currently work.

**Comment by TyrenDe** [comment]
Note: Other tests fail due to API throttling and such.  For example, if you try to run all the chat tests, some will fail because the API responds with a message telling you to wait and try your message again.
