### ISSUE TITLE
Sending whisper doesn't appear to be working.

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/StreamingClientLibrary#71]
When trying to use the SendWhisper method it completes successfully but the user never receives the whisper.

When looking at the events, it looks like the message was sent out to Twitch correctly.
ChatClient_OnSentOccurred: PRIVMSG #archonaut_ :.w trezthemodgod  trezthemodgod - this is a test

Is that command correct or should it be:  

PRIVMSG #archonaut_ :/w trezthemodgod  trezthemodgod - this is a test

**Comment by mphacker** [comment]
Ok.. I see that using the dot and not the slash is the correct format.  Very odd that the bot is unable to whisper people.

**Comment by SaviorXTanren** [comment]
There's also a LOT more nuances to Twitch whispers than there are on Mixer. There's limit issues, settings that block whispers, permission issues, etc. and error messaging is not are rich on Twitch.

EX: https://twitter.com/TwitchSupport/status/1042873432382160896

**Comment by mphacker** [comment]
It seems like they are a bit hit or miss when being sent by the bot.  I am not seeing any errors or data coming back via notifications showing that something is wrong.  Sometimes it sends... sometimes it doesn't.   Gotta love Twitch IRC API stuff.

**Comment by SaviorXTanren** [comment]
Yea, there's definitely going to be some feeling out time for adjusting to Twitch with stuff like this. I have yet to see any packets get sent back on a failed whisper and I don't see any way to get that information specifically. My general recommendation has been to avoid whispers unless absolutely necessarily, it's reason why we're phasing them out from normal Mix It Up usage unless explicitly set by the streamer.

**Comment by mphacker** [comment]
I was using it very infrequently previously, so gives me a reason to start avoiding it.
