### ISSUE TITLE
GetClips dates are passed with wrong format

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/StreamingClientLibrary#72]
GetClips startedAt and endedAt dates are not passed in RFC3339 format.  Need to append a "Z" to the end of the date string.

**Comment by mphacker** [comment]
Submitted a pull request, but there might be a better way to ensure RFC3339 format.   I have seen recommendations to do something like `ToString("yyyy-MM-dd'T'HH:mm:ss.fffzzz", DateTimeFormatInfo.InvariantInfo)` 

Thoughts?

**Comment by SaviorXTanren** [comment]
PR Reference: #73

Sounds perfectly reasonable, trying to get datetimes formatted correctly to text is always a bit tricky to get right. If there's other areas where there's use for this, we can eventually add it in to the extensions class that ToUTCISO8601String() is a part of.
