### ISSUE TITLE
GetBitsLeaderboard doesn't work if started_at is not provided.

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/StreamingClientLibrary#81]
Tonight I found out that the Twitch bits leaderboard API doesn't work correctly unless the started_at parameter is passed in.  This is contrary to what is stated in their documentation.  The started_at parameter is required for all periods except for all.  

The started_at parameter is a bit of a strangely named one too.  If the period is set to year then the started_at parameter will return a leaderboard for the past 12 months ending on the started_at date.

Not sure if anything should be done in the Twitch library to validate that started_at is supplied.

**Comment by SaviorXTanren** [comment]
I'd rather not, as there's a chance that Twitch could fix the issue at some point and then we're just doing an unnecessary check. That  said, worth reporting to Twitch at least for them to either fix it or update the documentation.
