### ISSUE TITLE
Update channel points

### ISSUE THREAD

**Issue by Sabuto** [SaviorXTanren/StreamingClientLibrary#94]
Hey so i am trying to allow users to update their channel points through my app, when i create a channel point i new up a `UpdatableCustomChannelPointRewardModel` and send it through and then store the `CustomChannelPointRewardModel`, similar to how mixer does it, now when i try and update a channel point i use the `NewAPI.ChannelPoints.UpdateCustomReward();` method. withg the required arguments, the last argument is a newed up `UpdatableCustomChannelPointRewardModel` with values from the holding `CustomChannelPointRewardModel` but i keep getting `HttpRestRequestException` with this output, any ideas?

```
System.ArgumentException: Could not determine JSON object type for type Twitch.Base.Models.NewAPI.ChannelPoints.UpdatableCustomChannelPointRewardModel.
   at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current, Object value)
   at Newtonsoft.Json.Linq.JValue..ctor(Object value)
   at Newtonsoft.Json.Linq.JContainer.CreateFromContent(Object content)
   at Newtonsoft.Json.Linq.JContainer.TryAddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Newtonsoft.Json.Linq.JObject..ctor(Object content)
   at Twitch.Base.Services.NewAPI.ChannelPointsService.UpdateCustomReward(UserModel broadcaster, Guid rewardID, UpdatableCustomChannelPointRewardModel reward)
```

Edit: I suppose i should actually include some of my code too:
I have `public CustomChannelPointRewardModel Reward`

then i have:

```cs
var update = new UpdatableCustomChannelPointRewardModel
            {
                is_max_per_stream_enabled = Reward.max_per_stream_setting.is_enabled,
                max_per_stream = Reward.max_per_stream_setting.max_per_stream,
                is_max_per_user_per_stream_enabled = Reward.max_per_user_per_stream_setting.is_enabled,
                max_per_user_per_stream =
                    Reward.max_per_user_per_stream_setting.max_per_user_per_stream,
                is_global_cooldown_enabled = Reward.global_cooldown_setting.is_enabled,
                global_cooldown_seconds = Reward.global_cooldown_setting.global_cooldown_seconds,
                cost = Reward.cost, title = Name, is_enabled = Reward.is_enabled,
                background_color = Reward.background_color, prompt = Reward.prompt,
                is_user_input_required = Reward.is_user_input_required,
                should_redemptions_skip_request_queue = Reward.should_redemptions_skip_request_queue,
                is_paused = Reward.is_paused
            };
            var test = await _mainSessions.TwitchService.UpdateChannelPoints(_mainSessions.TwitchNewApi,
                Reward.id, update
            );
```

and `UpdateChannelPoints` calls the `NewAPI.ChannelPoints.UpdateCustomReward();` method

for context when i create the channelpoint i only pass through the title, cost and is_enabled

**Comment by SaviorXTanren** [comment]
It doesn't look like you're updating much of the information, so using that specific method is overkill. Consider using the other one where you can simply supply a JObject of the fields you actually want to update.

**Comment by Sabuto** [comment]
I didnt actually notice the other method thanks :), but also the Reward is tied to the user interface and is updated there so when this method is called it is passing new information but i will check it out thanks :D
