### ISSUE TITLE
Twitch GetCustomRewardsRedemptions - Incorrect endpoint

### ISSUE THREAD

**Issue by mhackermsft** [SaviorXTanren/StreamingClientLibrary#97]
It appears that GetCustomRewardsRedemptions method for Twitch is using the wrong API endpoint and therefore returning no real results.    The URL being used is channel_points/custom_rewards but it appears it should be channel_points/custom_rewards/redemptions

Am I mistaken?  If you confirm this is an issue, I can fix and do a pull request.

**Comment by SaviorXTanren** [comment]
Most likely just a typo when they were added:

https://github.com/SaviorXTanren/StreamingClientLibrary/commit/49cdd4ef005a5ceec1c85012dd498cecc10a4853
