### ISSUE TITLE
New to this library

### ISSUE THREAD

**Issue by Caliente1337** [SaviorXTanren/StreamingClientLibrary#98]
Hello, i am new with that library and i have the following questions:

Can the bot reward  a role to the user if he casts 50k mana spells?

Talking about the trovo api. 

Thank you.

**Comment by SaviorXTanren** [comment]
So this isn't a bot, this is code library you would use in a program you develop. Those two parts of your question though are two separate things, they're not really related. You'll want read up on the Trovo developer docs for information about these:

https://developer.trovo.live/docs/APIs.html

You would use the Chat Client to listen for a custom spell packet:

https://developer.trovo.live/docs/Chat%20Service.html#_3-4-chat-message-types-and-samples

and then use that same chat client to send a "/addrole <USERNAME>" command to chat to give the role to the user.
