### ISSUE TITLE
Message delete

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/StreamingClientLibrary#99]
I think there is a bug in the Twitch library for deleting messages.  

In ChatService.cs the method DeleteChatMessage is doing a delete post on the announcement endpoint.   I looked at the Twitch API Spec and I am not seeing any new Chat API for deleting a message.

**Comment by SaviorXTanren** [comment]
So this is the new API for it:

https://dev.twitch.tv/docs/api/reference#delete-chat-messages

It's part of the IRC deprecation that Twitch is doing. Looks to be like just a bad copy-paste, I'll have a nuget update shortly for it:

https://github.com/SaviorXTanren/StreamingClientLibrary/commit/6accdfc6b17cfb77499bdc8f4bdbe4dea2560934

**Comment by mphacker** [comment]
I was just about to submit a PR for that.  Thanks for jumping on it quick.  An updated nuget is greatly appreciated.  Thank you!
